name: teleport-kube-agent-app
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/teleport-kube-agent-app
  tag: v0.0.1
  pullPolicy: IfNotPresent
