apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm
  contents:
  - path: teleport-kube-agent
    helmChart:
      name: "teleport-kube-agent"
      version: "16.1.7"
      repository:
        url: https://charts.releases.teleport.dev
    newRootPath: .
    includePaths:
    - templates/*
    - values.yaml
    - values.schema.json
    - Chart.yaml
