version: 2.1
orbs:
  architect: giantswarm/architect@5.2.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          name: "package and push teleport-kube-agent-app chart"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "teleport-kube-agent"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
