apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
  - Egress
  - Ingress
