apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    {{- include "labels.common" . | nindent 4 }}
  {{- if .Values.extraLabels.service }}
    {{- toYaml .Values.extraLabels.service | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations.service }}
  annotations:
    {{- toYaml .Values.annotations.service | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: diag
    port: 3000
    targetPort: diag
    protocol: TCP