apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    {{- include "labels.common" . | nindent 4 }}
  {{- if (index .Values "teleport-kube-agent" "extraLabels" "service") }}
    {{- toYaml (index .Values "teleport-kube-agent" "extraLabels" "service") | nindent 4 }}
  {{- end }}
  {{- if (index .Values "teleport-kube-agent" "annotations" "service") }}
  annotations:
    {{- toYaml (index .Values "teleport-kube-agent" "annotations" "service") | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: diag
    port: 3000
    targetPort: diag
    protocol: TCP
