apiVersion: v2
appVersion: 0.0.1

name: teleport-kube-agent

description: A Helm chart for Teleport Kubernetes access.

type: application

keywords:
  - Teleport

home: https://github.com/giantswarm/teleport-kube-agent-app

icon: https://s.giantswarm.io/app-icons/teleport/1/light.png

sources:
- https://github.com/gravitational/teleport
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: bigmac
maintainers:
  - name: giantswarm/team-bigmac
    email: team-bigmac@giantswarm.io
