checks:
  addAllBuiltIn: true
  exclude:
    - "dnsconfig-options"
    - "no-anti-affinity"
    - "no-node-affinity"
    - "no-rolling-update-strategy"
    - "non-isolated-pod"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "use-namespace"