checks:
  addAllBuiltIn: true
  exclude:
    - "dnsconfig-options"
    - "no-anti-affinity"
    - "no-node-affinity"
    - "no-rolling-update-strategy"
    - "non-isolated-pod"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "use-namespace"
    - "no-liveness-probe"
    - "no-readiness-probe"
    - "access-to-secrets"
    - "required-annotation-email"
    - "required-label-owner"
    - "pdb-unhealthy-pod-eviction-policy"